---

config:
  backup: true
  banner: false
  check_version: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_bash:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_config:
    src: bash/config
    dst: ~/.config/bash
  f_dotdrop:
    src: ../dotdrop.sh
    dst: ~/.bin/dotdrop.sh
  f_gitconfig:
    src: git/gitconfig
    dst: ~/.gitconfig
  f_nvim:
    src: nvim
    dst: ~/.config/nvim
  f_profile:
    src: profile/profile
    dst: ~/.profile
  f_screen:
    src: screen/screenrc
    dst: ~/.screenrc
  f_tmux:
    src: tmux/tmux.conf
    dst: ~/.tmux.conf
  f_wezterm:
    src: wezterm/wezterm.lua
    dst: ~/.wezterm.lua
profiles:
  linux:
    dotfiles:
    - f_dotdrop
    - f_profile
    - f_bash
    - f_bash_config
    - f_gitconfig
    - f_nvim
    - f_tmux
    - f_screen
    - f_wezterm
