# https://dotdrop.readthedocs.io/en/latest/config/config-config/
config:
  backup: true
  banner: false
  check_version: false
  create: true
  dotpath: files
dotfiles:
  f_bash:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_config:
    src: bash/config
    dst: ~/.config/bash
  f_gitconfig:
    src: git/gitconfig
    dst: ~/.gitconfig
  f_nvim:
    src: nvim
    dst: ~/.config/nvim
    upignore:
      - ~/.config/nvim/lazy-lock.json
    cmpignore:
      - ~/.config/nvim/lazy-lock.json
  f_profile:
    src: profile/profile
    dst: ~/.profile
  f_profile_config:
    src: profile/config
    dst: ~/.config/profile
  f_screen:
    src: screen/screenrc
    dst: ~/.screenrc
  f_tmux:
    src: tmux/tmux.conf
    dst: ~/.tmux.conf
  f_wezterm:
    src: wezterm/wezterm.lua
    dst: ~/.wezterm.lua
  d_completion.d:
    src: config/bash/completion.d
    dst: ~/.config/bash/completion.d
profiles:
  linux:
    dotfiles:
      - f_profile
      - f_profile_config
      - f_bash
      - f_bash_config
      - f_gitconfig
      - f_nvim
      - f_tmux
      - f_screen
      - f_wezterm
  windows:
    dotfiles:
      - f_gitconfig
      - f_nvim
  Azathoth:
    dotfiles:
      - d_completion.d
