return {
  "snacks.nvim",
  enabled = true,
  opts = {
    animate = { enabled = false, },
    bigfile = { enabled = true, },
    bufdelete = { enabled = true, },
    dashboard = { enabled = false, },
    debug = { enabled = false, },
    dim = { enabled = false, },
    explorer = { enabled = false, },
    git = { enabled = true, },
    gitbrowse = { enabled = false, },
    image = { enabled = false, },
    indent = { enabled = true, },
    input = { enabled = false },
    layout = { enabled = false },
    lazygit = { enabled = false },
    notifier = { enabled = false },
    notify = { enabled = false, },
    picker = { enabled = false, },
    profiler = { enabled = false, },
    quickfile = { enabled = false, },
    rename = { enabled = false, },
    scope = { enabled = false, },
    scratch = { enabled = false, },
    scroll = { enabled = false, },
    statuscolumn = { enabled = false, },
    terminal = { enabled = false, },
    toggle = { enabled = false, },
    util = { enabled = true, },
    win = { enabled = false, },
    words = { enabled = false, },
    zen = { enabled = false, },
  },
}
