HOME_BASH="${HOME}/.config/bash"

# If not running interactively, don't do anything
case $- in
*i*) ;;
*)
	return
	;;
esac

# No duplicates in history
HISTCONTROL=ignoreboth

# Append to history
shopt -s histappend

# History size
HISTSIZE=1000
HISTFILESIZE=2000

# Update window size
shopt -s checkwinsize

# Nicer `less` for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Bash functions
. ${HOME_BASH}/git_support

# Prompt
. ${HOME_BASH}/prompt

# Aliases
. ${HOME_BASH}/aliases

# Completion
. ${HOME_BASH}/completion
