HOME_BASH="${HOME}/.config/bash"

# If not running interactively, don't do anything
case $- in
*i*) ;;
*)
	return
	;;
esac

# No duplicates in history
HISTCONTROL=ignoreboth

# Append to history
shopt -s histappend

# History size
HISTSIZE=1000
HISTFILESIZE=2000

# Update window size
shopt -s checkwinsize

# Nicer `less` for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Bash functions
. ${HOME_BASH}/functions

# Prompt
. ${HOME_BASH}/prompt

# Aliases
. ${HOME_BASH}/aliases

# Completion
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi
